server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location /api/configurations {
        proxy_pass http://configuration-service:8081;
        proxy_set_header Host $host;
    }

    location /api/analyses {
        proxy_pass http://analysis-management-service:8082;
        proxy_set_header Host $host;
    }

    location /monitor/configuration/ {
        proxy_pass http://configuration-service:8081/;
        proxy_connect_timeout 1s;
        proxy_read_timeout 2s;
        proxy_no_cache 1;
        add_header Cache-Control "no-store" always;
    }

    location /monitor/analysis-management/ {
        proxy_pass http://analysis-management-service:8082/;
        proxy_connect_timeout 1s;
        proxy_read_timeout 2s;
        proxy_no_cache 1;
        add_header Cache-Control "no-store" always;
    }

    location /monitor/fluid/ {
        proxy_pass http://fluid-analysis-service:8083/;
        proxy_connect_timeout 1s;
        proxy_read_timeout 2s;
        proxy_no_cache 1;
        add_header Cache-Control "no-store" always;
    }

    location /monitor/thermal/ {
        proxy_pass http://thermal-analysis-service:8084/;
        proxy_connect_timeout 1s;
        proxy_read_timeout 2s;
        proxy_no_cache 1;
        add_header Cache-Control "no-store" always;
    }

    location /monitor/electrical/ {
        proxy_pass http://electrical-analysis-service:8085/;
        proxy_connect_timeout 1s;
        proxy_read_timeout 2s;
        proxy_no_cache 1;
        add_header Cache-Control "no-store" always;
    }

    location /monitor/engine-management/ {
        proxy_pass http://engine-management-analysis-service:8086/;
        proxy_connect_timeout 1s;
        proxy_read_timeout 2s;
        proxy_no_cache 1;
        add_header Cache-Control "no-store" always;
    }

    location / {
        try_files $uri /index.html;
    }
}
